### ISSUE TITLE
multiple channels

### ISSUE THREAD

**Issue by ghost** [ZarTek-Creole/TCL-Youtube-Link#2]
it is set/allow to specific channel only.. but still works in multiple channel..
can you please check the bug and fix it..

 set Channels(Allow)         "#mychannel"

**Comment by ZarTek-Creole** [comment]
> it is set/allow to specific channel only.. but still works in multiple channel..
> can you please check the bug and fix it..
> 
> set Channels(Allow) "#mychannel"

It only listens for links on defined channels. Thanks for this bug report.
Please give me feedback that it is working correctly for your expectations.

**Comment by ghost** [comment]
it works perfect now .. thank you for the update.

**Comment by ZarTek-Creole** [comment]
you're welcome
