### ISSUE TITLE
Add variable \${MUSIC_DURATION}) and \${MUSIC_VIEWED}" for Annonce(Message_Search)

### ISSUE THREAD

**Issue by samledieu** [ZarTek-Creole/TCL-Youtube-Link#3]
hello can you modify the tcl and add the song's direction and the number of views
thank you

**Comment by samledieu** [comment]
[Youtube_Link.txt](https://github.com/MalaGaM/TCL-Youtube-Link/files/7186829/Youtube_Link.txt)

**Comment by ZarTek-Creole** [comment]
Lors d'une recherche avoir les variables \${MUSIC_DURATION} et \${MUSIC_VIEWED} disponible pour l'Annonce(Message_Search) directement.

L'API YouTube V3 ne donne pas cette information dans les recherche. Il est obliger de faire une requête supplémentaire a chaque résultat.
